-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 11:02:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biosearcher
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biosearcher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biosearcher` DEFAULT CHARACTER SET utf8 ;
USE `Biosearcher` ;

-- -----------------------------------------------------
-- Table `Biosearcher`.`Afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Afiliado` (
  `cedulaIdentidad` INT NOT NULL,
  `idMatricula` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  PRIMARY KEY (`cedulaIdentidad`),
  UNIQUE INDEX `cedulaIdentidad_UNIQUE` (`cedulaIdentidad` ASC) VISIBLE,
  UNIQUE INDEX `idMatricula_UNIQUE` (`idMatricula` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biosearcher`.`Afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Afiliacion` (
  `idAfiliacion` INT NOT NULL AUTO_INCREMENT,
  `nombreAfiliacion` VARCHAR(60) NOT NULL,
  `ciAfiliado` INT NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idAfiliacion`),
  INDEX `ciAfiliadoForaneo_idx` (`ciAfiliado` ASC) VISIBLE,
  UNIQUE INDEX `idAfiliacion_UNIQUE` (`idAfiliacion` ASC) VISIBLE,
  CONSTRAINT `ciAfiliadoForaneo`
    FOREIGN KEY (`ciAfiliado`)
    REFERENCES `Biosearcher`.`Afiliado` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biosearcher`.`Negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Negocio` (
  `idNegocio` INT NOT NULL AUTO_INCREMENT,
  `idAfiliado` INT NOT NULL,
  `nombreNegocio` VARCHAR(45) NOT NULL,
  `rubro` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idNegocio`),
  UNIQUE INDEX `idNegocio_UNIQUE` (`idNegocio` ASC) VISIBLE,
  INDEX `idAfiliacionForaneo_idx` (`idAfiliado` ASC) VISIBLE,
  CONSTRAINT `idAfiliacionForaneo`
    FOREIGN KEY (`idAfiliado`)
    REFERENCES `Biosearcher`.`Afiliacion` (`ciAfiliado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biosearcher`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `idNegocio` INT NOT NULL,
  `direccionLocal` VARCHAR(100) NOT NULL,
  `nombreEncargado` VARCHAR(45) NOT NULL,
  `apellidoEncargado` VARCHAR(45) NOT NULL,
  `ciEncargado` INT NOT NULL,
  INDEX `idNegocio_idx` (`idNegocio` ASC) VISIBLE,
  PRIMARY KEY (`idLocal`),
  UNIQUE INDEX `idLocal_UNIQUE` (`idLocal` ASC) VISIBLE,
  CONSTRAINT `idNegocioForaneo`
    FOREIGN KEY (`idNegocio`)
    REFERENCES `Biosearcher`.`Negocio` (`idNegocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biosearcher`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Pagos` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `cedulaIdentidad` INT NOT NULL,
  `fechaHoraPagoCuota` DATETIME NOT NULL,
  `tipoDePago` ENUM("Mensual", "Matricula") NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `ciForaneo_idx` (`cedulaIdentidad` ASC) VISIBLE,
  UNIQUE INDEX `idPago_UNIQUE` (`idPago` ASC) VISIBLE,
  CONSTRAINT `ciForaneo`
    FOREIGN KEY (`cedulaIdentidad`)
    REFERENCES `Biosearcher`.`Afiliado` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biosearcher`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biosearcher`.`Usuarios` (
  `nombreUsuario` VARCHAR(100) NOT NULL,
  `claveUsuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
