-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 20:52:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NombreTemporal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NombreTemporal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NombreTemporal` DEFAULT CHARACTER SET utf8 ;
USE `NombreTemporal` ;

-- -----------------------------------------------------
-- Table `NombreTemporal`.`Afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Afiliado` (
  `cedulaIdentidad` INT NOT NULL,
  `idMatricula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  PRIMARY KEY (`cedulaIdentidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Afiliacion` (
  `idAfiliacion` INT NOT NULL,
  `nombreAfiliacion` VARCHAR(60) NOT NULL,
  `ciAfiliado` INT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idAfiliacion`),
  INDEX `ciAfiliadoForaneo_idx` (`ciAfiliado` ASC) VISIBLE,
  CONSTRAINT `ciAfiliadoForaneo`
    FOREIGN KEY (`ciAfiliado`)
    REFERENCES `NombreTemporal`.`Afiliado` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Negocio` (
  `idNegocio` INT NOT NULL AUTO_INCREMENT,
  `idAfiliadon` INT NOT NULL,
  `rubro` VARCHAR(50) NOT NULL,
  `nombreNegocio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idNegocio`),
  INDEX `idAfiliacionForaneo_idx` (`idAfiliadon` ASC) VISIBLE,
  CONSTRAINT `idAfiliacionForaneo`
    FOREIGN KEY (`idAfiliadon`)
    REFERENCES `NombreTemporal`.`Afiliacion` (`idAfiliacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `ciEncargado` INT NOT NULL,
  `idNegocio` INT NOT NULL,
  `direccionLocal` VARCHAR(100) NOT NULL,
  INDEX `idNegocio_idx` (`idNegocio` ASC) VISIBLE,
  INDEX `ciEncargadoForaneo_idx` (`ciEncargado` ASC) VISIBLE,
  PRIMARY KEY (`idLocal`),
  CONSTRAINT `idNegocioForaneo`
    FOREIGN KEY (`idNegocio`)
    REFERENCES `NombreTemporal`.`Negocio` (`idNegocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ciEncargadoForaneo`
    FOREIGN KEY (`ciEncargado`)
    REFERENCES `NombreTemporal`.`Afiliado` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Pagos` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `cedulaIdentidad` INT NOT NULL,
  `fechaHoraPagoCuota` DATETIME NOT NULL,
  `tipoDePago` ENUM("Mensual", "Matricula") NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `ciForaneo_idx` (`cedulaIdentidad` ASC) VISIBLE,
  CONSTRAINT `ciForaneo`
    FOREIGN KEY (`cedulaIdentidad`)
    REFERENCES `NombreTemporal`.`Afiliado` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Usuarios` (
  `nombreUsuario` VARCHAR(100) NOT NULL,
  `claveUsuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
