-- MySQL Script generated by MySQL Workbench
-- Fri Jul  8 00:24:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NombreTemporal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NombreTemporal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NombreTemporal` DEFAULT CHARACTER SET utf8 ;
USE `NombreTemporal` ;

-- -----------------------------------------------------
-- Table `NombreTemporal`.`Afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Afiliacion` (
  `idAfiliacion` INT NOT NULL,
  `cedulaIdentidad` INT NOT NULL,
  `primeraCuotaPagada` DATETIME NOT NULL,
  `pagoMatricula` DATETIME NOT NULL,
  PRIMARY KEY (`idAfiliacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Pagos` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `pagoCuota` DATETIME NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Persona` (
  `cedulaIdentidad` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  PRIMARY KEY (`cedulaIdentidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Afiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Afiliado` (
  `idAfiliado` INT NOT NULL,
  `idAfiliacion` INT NULL,
  `idLocal` INT NOT NULL,
  `idNegocio` INT NOT NULL,
  `idPago` INT NOT NULL,
  `idMatricula` INT NOT NULL,
  PRIMARY KEY (`idAfiliado`),
  INDEX `idPago_idx` (`idPago` ASC) VISIBLE,
  CONSTRAINT `idAfiliacionForaneo`
    FOREIGN KEY (`idAfiliacion`)
    REFERENCES `NombreTemporal`.`Afiliacion` (`idAfiliacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPagoForaneo`
    FOREIGN KEY (`idPago`)
    REFERENCES `NombreTemporal`.`Pagos` (`idPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAfiliadoForaneo`
    FOREIGN KEY (`idAfiliado`)
    REFERENCES `NombreTemporal`.`Persona` (`cedulaIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`TipoDeNegocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`TipoDeNegocio` (
  `idTipoDeNegocio` INT NOT NULL AUTO_INCREMENT,
  `nombreNegocio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idTipoDeNegocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Negocio` (
  `idNegocio` INT NOT NULL AUTO_INCREMENT,
  `idTipoDeNegocio` INT NOT NULL,
  `idAfiliado` INT NOT NULL,
  PRIMARY KEY (`idNegocio`),
  CONSTRAINT `idTipoDeNegocioForaneo`
    FOREIGN KEY (`idTipoDeNegocio`)
    REFERENCES `NombreTemporal`.`TipoDeNegocio` (`idTipoDeNegocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `idNegocio` INT NOT NULL,
  `direccionLocal` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idLocal`),
  INDEX `idNegocio_idx` (`idNegocio` ASC) VISIBLE,
  CONSTRAINT `idNegocioForaneo`
    FOREIGN KEY (`idNegocio`)
    REFERENCES `NombreTemporal`.`Negocio` (`idNegocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Encargado` (
  `ciEncargado` INT NOT NULL,
  `idLocal` INT NOT NULL,
  `nombreEncargado` VARCHAR(45) NOT NULL,
  `localesACargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ciEncargado`),
  INDEX `idLocal_idx` (`idLocal` ASC) VISIBLE,
  CONSTRAINT `idLocalForaneo`
    FOREIGN KEY (`idLocal`)
    REFERENCES `NombreTemporal`.`Local` (`idLocal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ciEncargadoForaneo`
    FOREIGN KEY (`ciEncargado`)
    REFERENCES `NombreTemporal`.`Persona` (`cedulaIdentidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NombreTemporal`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NombreTemporal`.`Usuarios` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreDeUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
